project:
  type: website

website:
  title: Drake Lab
  navbar:
    collapse: false
    tools-collapse: false
    search: false
    right:
      - text: About
        href: http://example.com
      - icon: github
        href: http://github.com

profile: 
  default: layer